# Mar-2026, Claude and Pat Welch, pat@mousebrains.com
"""Validate Python epsilon against MATLAB get_diss_odas output.

Compares Python dissipation results against *_validation.nc files
generated by matlab/generate_validation_nc.m.

Key differences accounted for:
  - MATLAB shear is du/dz (divided by speed^2); Python shear is U^2 * du/dz.
    Both use the same spectral pipeline, so epsilon should match despite
    different shear conventions (shear is converted to wavenumber spectra
    internally, and the speed factor cancels).
  - Profile detection may differ slightly at boundaries, so profiles are
    matched by median pressure rather than by index.
  - Viscosity: both use visc35(T) by default.
"""

import os
from pathlib import Path

import numpy as np
import pytest

netCDF4 = pytest.importorskip("netCDF4")

pytestmark = pytest.mark.matlab

VMP_DIR = Path(__file__).parents[1] / "VMP"

# Discover validation files.
# MAX_MATLAB_FILES controls how many files to test (default 5, 0 = all).
_val_files = sorted(VMP_DIR.glob("*_validation.nc")) if VMP_DIR.exists() else []
_max = int(os.environ.get("MAX_MATLAB_FILES", "12"))
if _max and len(_val_files) > _max:
    _step = len(_val_files) / _max
    _val_files = [_val_files[int(i * _step)] for i in range(_max)]


def _file_id(path):
    stem = path.stem.replace("_validation", "")
    return stem.split("_")[-1]


def _load_validation(nc_path: Path) -> dict:
    """Load a *_validation.nc file.

    Returns a dict with:
      - scalar attributes (fs_fast, fs_slow, n_profiles, etc.)
      - per-profile lists (eps_all, nu_all, etc.) indexed by profile number
    """
    out = {}
    with netCDF4.Dataset(str(nc_path), "r") as ds:
        # Global attributes
        for attr in ds.ncattrs():
            out[attr] = ds.getncattr(attr)

        # Root-level variables
        for vname in ds.variables:
            out[vname] = np.squeeze(ds.variables[vname][:])

        # Per-profile groups → lists matching old cell-array layout
        n_profiles = int(out["n_profiles"])
        list_keys = [
            "eps_all", "K_max_all", "FM_all", "mad_all", "method_all",
            "nu_all", "speed_all", "P_mean_all", "T_mean_all", "t_mean_all",
            "K_all", "F_all", "spec_sh_all",
        ]
        for k in list_keys:
            out[k] = [None] * n_profiles

        for pi in range(n_profiles):
            grp_name = f"profile_{pi + 1:03d}"
            if grp_name not in ds.groups:
                continue
            grp = ds.groups[grp_name]

            out["eps_all"][pi] = np.squeeze(grp.variables["epsilon"][:])
            out["K_max_all"][pi] = np.squeeze(grp.variables["K_max"][:])
            out["FM_all"][pi] = np.squeeze(grp.variables["FM"][:])
            out["mad_all"][pi] = np.squeeze(grp.variables["mad"][:])
            out["method_all"][pi] = np.squeeze(grp.variables["method"][:])
            out["nu_all"][pi] = np.squeeze(grp.variables["nu"][:])
            out["speed_all"][pi] = np.squeeze(grp.variables["speed"][:])
            out["P_mean_all"][pi] = np.squeeze(grp.variables["P_mean"][:])
            out["T_mean_all"][pi] = np.squeeze(grp.variables["T_mean"][:])
            out["t_mean_all"][pi] = np.squeeze(grp.variables["t_mean"][:])
            out["K_all"][pi] = np.squeeze(grp.variables["K"][:])
            out["F_all"][pi] = np.squeeze(grp.variables["F"][:])
            if "spec_shear_clean" in grp.variables:
                out["spec_sh_all"][pi] = np.squeeze(
                    grp.variables["spec_shear_clean"][:]
                )
            else:
                out["spec_sh_all"][pi] = np.array([])

    return out


def _match_profiles(py_results, val):
    """Match Python and MATLAB profiles by mean time of first estimate.

    Returns list of (py_index, ml_index) tuples for matched profiles.
    Uses the time of the first estimate to identify corresponding profiles,
    since many profiles reach similar depths and pressure alone is ambiguous.
    """
    n_ml = int(val["n_profiles"])

    # Get start time for each MATLAB profile
    ml_times = []
    for i in range(n_ml):
        t = val["t_mean_all"][i]
        t = np.atleast_1d(t)
        valid = t[np.isfinite(t)]
        ml_times.append(valid[0] if len(valid) > 0 else np.nan)

    # Get start time for each Python profile
    py_times = []
    for ds in py_results:
        t = ds.coords["t"].values
        valid = t[np.isfinite(t)]
        py_times.append(valid[0] if len(valid) > 0 else np.nan)

    # Greedy matching by closest start time
    matched = []
    used_ml = set()
    for pi, py_t in enumerate(py_times):
        if np.isnan(py_t):
            continue
        best_mi = None
        best_diff = np.inf
        for mi, ml_t in enumerate(ml_times):
            if mi in used_ml or np.isnan(ml_t):
                continue
            diff = abs(py_t - ml_t)
            if diff < best_diff:
                best_diff = diff
                best_mi = mi
        # Match if start times within 60 seconds
        if best_mi is not None and best_diff < 60.0:
            matched.append((pi, best_mi))
            used_ml.add(best_mi)

    return matched


@pytest.fixture(scope="module", params=_val_files, ids=[_file_id(p) for p in _val_files])
def validation_pair(request):
    """Yield (p_path, validation_dict) for each file with validation data."""
    val_path = request.param
    stem = val_path.stem.replace("_validation", "")
    p_path = val_path.with_name(stem + ".p")
    if not p_path.exists():
        pytest.skip(f"No .p file for {val_path.name}")
    val = _load_validation(val_path)
    return p_path, val


@pytest.fixture(scope="module")
def matched_results(validation_pair, cached_get_diss):
    """Run get_diss and match profiles against MATLAB. Cache per file."""
    p_path, val = validation_pair
    results = cached_get_diss(p_path, fft_length=256, goodman=True)
    matched = _match_profiles(results, val)
    return results, val, matched


class TestEpsilonVsMatlab:
    """Compare Python epsilon output against MATLAB get_diss_odas."""

    def test_profile_count(self, matched_results):
        """Python and MATLAB should detect similar number of profiles."""
        results, val, matched = matched_results
        ml_n = int(val["n_profiles"])
        py_n = len(results)
        assert abs(py_n - ml_n) <= 3, f"Profile count: Python {py_n} vs MATLAB {ml_n}"

    def test_most_profiles_matched(self, matched_results):
        """Most profiles should match between Python and MATLAB."""
        results, val, matched = matched_results
        ml_n = int(val["n_profiles"])
        py_n = len(results)
        n_matched = len(matched)
        min_total = min(ml_n, py_n)
        if min_total >= 3:
            assert n_matched >= min_total * 0.7, f"Only {n_matched}/{min_total} profiles matched"

    def test_epsilon_order_of_magnitude(self, matched_results):
        """Epsilon values should agree within ~1 decade for matched profiles."""
        results, val, matched = matched_results

        for pi, mi in matched:
            py_eps = results[pi]["epsilon"].values  # (n_probe, n_est)
            ml_eps = val["eps_all"][mi]  # (n_est, n_shear) from NetCDF

            if ml_eps.ndim == 1:
                ml_eps = ml_eps.reshape(-1, 1)
            ml_eps = ml_eps.T  # -> (n_shear, n_est)

            n_est = min(py_eps.shape[1], ml_eps.shape[1])
            if n_est == 0:
                continue

            for ci in range(min(py_eps.shape[0], ml_eps.shape[0])):
                py_e = py_eps[ci, :n_est]
                ml_e = ml_eps[ci, :n_est]
                valid = np.isfinite(py_e) & np.isfinite(ml_e) & (py_e > 0) & (ml_e > 0)
                if np.sum(valid) < 3:
                    continue
                log_diff = np.abs(np.log10(py_e[valid]) - np.log10(ml_e[valid]))
                median_diff = np.median(log_diff)
                assert median_diff < 1.0, (
                    f"py_prof {pi} / ml_prof {mi}, probe {ci}: "
                    f"median log10 epsilon diff {median_diff:.2f} > 1.0"
                )

    def test_epsilon_correlation(self, matched_results):
        """Python and MATLAB epsilon should be positively correlated.

        Differences arise from the shear convention (Python keeps U^2*du/dz,
        MATLAB uses du/dz) affecting Goodman cleaning and spectral fitting.
        We require moderate positive correlation (r > 0.3) per profile,
        and check that most profiles have good correlation (r > 0.7).
        """
        results, val, matched = matched_results
        all_corrs = []

        for pi, mi in matched:
            py_eps = results[pi]["epsilon"].values
            ml_eps = val["eps_all"][mi]
            if ml_eps.ndim == 1:
                ml_eps = ml_eps.reshape(-1, 1)
            ml_eps = ml_eps.T  # -> (n_shear, n_est)

            n_est = min(py_eps.shape[1], ml_eps.shape[1])
            if n_est < 20:
                continue

            for ci in range(min(py_eps.shape[0], ml_eps.shape[0])):
                py_e = py_eps[ci, :n_est]
                ml_e = ml_eps[ci, :n_est]
                valid = np.isfinite(py_e) & np.isfinite(ml_e) & (py_e > 0) & (ml_e > 0)
                if np.sum(valid) < 20:
                    continue
                corr = np.corrcoef(np.log10(py_e[valid]), np.log10(ml_e[valid]))[0, 1]
                all_corrs.append(corr)
                assert corr > 0.0, (
                    f"py_prof {pi} / ml_prof {mi}, probe {ci}: "
                    f"log10(eps) correlation {corr:.3f} <= 0"
                )

        # Most profile-probe pairs should have decent correlation
        if len(all_corrs) >= 5:
            frac_good = np.mean([c > 0.5 for c in all_corrs])
            assert frac_good > 0.6, f"Only {frac_good:.0%} of profiles have r > 0.5"

    def test_viscosity_match(self, matched_results):
        """Kinematic viscosity should match closely (both use visc35)."""
        results, val, matched = matched_results

        for pi, mi in matched:
            py_nu = results[pi]["nu"].values
            ml_nu = val["nu_all"][mi]
            n_est = min(len(py_nu), len(ml_nu))
            if n_est == 0:
                continue
            valid = np.isfinite(py_nu[:n_est]) & np.isfinite(ml_nu[:n_est])
            if np.sum(valid) < 3:
                continue
            # Compare median values (profile boundaries may shift estimates)
            py_med = np.median(py_nu[:n_est][valid])
            ml_med = np.median(ml_nu[:n_est][valid])
            rel_diff = abs(py_med - ml_med) / ml_med
            assert rel_diff < 0.05, (
                f"py_prof {pi} / ml_prof {mi}: median viscosity relative diff {rel_diff:.4f} > 0.05"
            )

    def test_speed_match(self, matched_results):
        """Mean speed per estimate should be similar for matched profiles."""
        results, val, matched = matched_results

        for pi, mi in matched:
            py_speed = results[pi]["speed"].values
            ml_speed = val["speed_all"][mi]
            n_est = min(len(py_speed), len(ml_speed))
            if n_est < 20:
                continue
            valid = (
                np.isfinite(py_speed[:n_est])
                & np.isfinite(ml_speed[:n_est])
                & (py_speed[:n_est] > 0.1)
                & (ml_speed[:n_est] > 0.1)
            )
            if np.sum(valid) < 20:
                continue
            corr = np.corrcoef(py_speed[:n_est][valid], ml_speed[:n_est][valid])[0, 1]
            assert corr > 0.75, f"py_prof {pi} / ml_prof {mi}: speed correlation {corr:.3f} < 0.75"

    def test_wavenumber_vectors(self, matched_results):
        """K = F/W wavenumber vectors should match between Python and MATLAB."""
        results, val, matched = matched_results

        for pi, mi in matched:
            py_K = results[pi]["K"].values  # (n_freq, n_est)
            ml_K = val["K_all"][mi]  # (n_est, n_freq) from NetCDF

            if ml_K.ndim == 1:
                continue  # single-estimate profile, skip
            ml_K = ml_K.T  # -> (n_freq, n_est)

            n_est = min(py_K.shape[1], ml_K.shape[1])
            n_freq = min(py_K.shape[0], ml_K.shape[0])
            if n_est == 0 or n_freq < 3:
                continue

            for j in range(min(n_est, 5)):  # spot-check first 5 estimates
                py_k = py_K[:n_freq, j]
                ml_k = ml_K[:n_freq, j]
                valid = np.isfinite(py_k) & np.isfinite(ml_k) & (py_k > 0) & (ml_k > 0)
                if np.sum(valid) < 3:
                    continue
                np.testing.assert_allclose(
                    py_k[valid],
                    ml_k[valid],
                    rtol=0.05,
                    err_msg=(f"py_prof {pi} / ml_prof {mi}, est {j}: K vectors differ by > 5%"),
                )

    def test_frequency_vectors(self, matched_results):
        """F frequency vectors should match between Python and MATLAB."""
        results, val, matched = matched_results

        for pi, mi in matched:
            py_F = results[pi]["F"].values  # (n_freq, n_est)
            ml_F = val["F_all"][mi]  # (n_est, n_freq) from NetCDF

            if ml_F.ndim == 1:
                continue
            ml_F = ml_F.T  # -> (n_freq, n_est)

            n_freq = min(py_F.shape[0], ml_F.shape[0])
            if n_freq < 3:
                continue

            # F vectors should be identical across estimates; check first
            py_f = py_F[:n_freq, 0]
            ml_f = ml_F[:n_freq, 0]
            valid = np.isfinite(py_f) & np.isfinite(ml_f)
            if np.sum(valid) < 3:
                continue
            np.testing.assert_allclose(
                py_f[valid],
                ml_f[valid],
                rtol=1e-10,
                err_msg=f"py_prof {pi} / ml_prof {mi}: F vectors differ",
            )

    def test_cleaned_shear_spectra(self, matched_results):
        """Cleaned shear spectra should agree in log-space for matched windows.

        Compares diagonal auto-spectra from the cleaned cross-spectral matrix.
        MATLAB stores the full (n_shear, n_shear) matrix; Python stores
        the diagonal.
        """
        results, val, matched = matched_results

        for pi, mi in matched:
            py_spec = results[pi]["spec_shear"].values  # (n_probe, n_freq, n_est)
            ml_spec_full = val["spec_sh_all"][mi]
            # MATLAB netcdf.putVar writes column-major bytes; the NetCDF
            # C-order shape is the reverse of MATLAB's, but the byte layout
            # means Python indexing [a,b,c,d] maps to MATLAB (d,c,b,a).
            # For 4D: Python shape (n_freq_label, 2, 2, n_est_label) but
            # data is accessed as [est, sh, sh, freq] (MATLAB memory order).

            if ml_spec_full.ndim < 4:
                continue

            # Last axis is freq (128+1), first axis is est
            n_est = min(py_spec.shape[2], ml_spec_full.shape[0])
            n_freq = min(py_spec.shape[1], ml_spec_full.shape[3])
            n_probe = min(py_spec.shape[0], ml_spec_full.shape[1])

            if n_est < 3:
                continue

            for ci in range(n_probe):
                log_diffs = []
                for j in range(n_est):
                    py_s = py_spec[ci, 1:n_freq, j]  # skip DC
                    ml_s = ml_spec_full[j, ci, ci, 1:n_freq]  # diagonal auto-spectrum
                    valid = np.isfinite(py_s) & np.isfinite(ml_s) & (py_s > 0) & (ml_s > 0)
                    if np.sum(valid) < 5:
                        continue
                    log_diff = np.abs(np.log10(py_s[valid]) - np.log10(ml_s[valid]))
                    log_diffs.extend(log_diff.tolist())

                if len(log_diffs) > 10:
                    median_diff = np.median(log_diffs)
                    assert median_diff < 0.3, (
                        f"py_prof {pi} / ml_prof {mi}, probe {ci}: "
                        f"median log10 spec diff {median_diff:.3f} > 0.3"
                    )

    def test_pressure_depth_range(self, matched_results):
        """Pressure ranges should be similar for matched profiles."""
        results, val, matched = matched_results

        for pi, mi in matched:
            py_P = results[pi]["P_mean"].values
            ml_P = val["P_mean_all"][mi]
            n_est = min(len(py_P), len(ml_P))
            if n_est == 0:
                continue
            valid_py = py_P[:n_est][np.isfinite(py_P[:n_est])]
            valid_ml = ml_P[:n_est][np.isfinite(ml_P[:n_est])]
            if len(valid_py) == 0 or len(valid_ml) == 0:
                continue
            py_max = valid_py.max()
            ml_max = valid_ml.max()
            if ml_max > 10:  # only check profiles deeper than 10 dbar
                ratio = py_max / ml_max
                assert 0.7 < ratio < 1.3, (
                    f"py_prof {pi} / ml_prof {mi}: max P ratio {ratio:.2f} "
                    f"(Python {py_max:.1f} vs MATLAB {ml_max:.1f})"
                )
