# Mar-2026, Claude and Pat Welch, pat@mousebrains.com
"""Validate Python pipeline against MATLAB/ODAS reference output.

Compares Python PFile channel conversion, profile detection, fall rate,
and epsilon extraction against *_p2mat.nc files generated by
matlab/generate_odas_p2mat_nc.m.
"""

import os
from pathlib import Path

import numpy as np
import pytest

netCDF4 = pytest.importorskip("netCDF4")

pytestmark = pytest.mark.matlab

VMP_DIR = Path(__file__).parents[1] / "VMP"

# Discover all matched _p2mat.nc / .p pairs.
# MAX_MATLAB_FILES controls how many files to test (default 5, 0 = all).
_pairs = []
if VMP_DIR.exists():
    for nc_path in sorted(VMP_DIR.glob("*_p2mat.nc")):
        stem = nc_path.stem.replace("_p2mat", "")
        p_path = nc_path.with_name(stem + ".p")
        if p_path.exists():
            _pairs.append((p_path, nc_path))

_max = int(os.environ.get("MAX_MATLAB_FILES", "12"))
if _max and len(_pairs) > _max:
    _step = len(_pairs) / _max
    _pairs = [_pairs[int(i * _step)] for i in range(_max)]


def _file_id(pair):
    return pair[0].stem.split("_")[-1]


def _load_p2mat(nc_path: Path) -> dict:
    """Load a *_p2mat.nc file."""
    out = {}
    with netCDF4.Dataset(str(nc_path), "r") as ds:
        for attr in ds.ncattrs():
            out[attr] = ds.getncattr(attr)
        for vname in ds.variables:
            out[vname] = np.squeeze(ds.variables[vname][:])
    return out


@pytest.fixture(scope="module", params=_pairs, ids=[_file_id(p) for p in _pairs])
def file_pair(request):
    """Yield (PFile, nc_dict, p_path) for each matched file pair."""
    p_path, nc_path = request.param
    from rsi_python.p_file import PFile

    pf = PFile(p_path)
    ref = _load_p2mat(nc_path)
    return pf, ref, p_path


# ---------------------------------------------------------------------------
# Metadata
# ---------------------------------------------------------------------------


class TestMetadata:
    def test_sampling_rates(self, file_pair):
        """Python and MATLAB should agree on sampling rates."""
        pf, mat, _ = file_pair
        np.testing.assert_allclose(pf.fs_fast, mat["fs_fast"], rtol=1e-10)
        np.testing.assert_allclose(pf.fs_slow, mat["fs_slow"], rtol=1e-10)

    def test_array_lengths(self, file_pair):
        """Fast and slow time series should have the same length."""
        pf, mat, _ = file_pair
        assert pf.t_fast.shape == mat["t_fast"].shape
        assert pf.t_slow.shape == mat["t_slow"].shape


# ---------------------------------------------------------------------------
# Channel conversion: slow-rate
# ---------------------------------------------------------------------------


class TestSlowChannels:
    """Compare slow-rate channels.

    With the Mudge & Lueck (1994) deconvolution now ported to Python,
    slow-rate channels (P, T1, T2) should match the MATLAB output exactly
    (to float64 precision).
    """

    def test_pressure(self, file_pair):
        """Pressure (P) should exactly match MATLAB P_slow."""
        pf, mat, _ = file_pair
        np.testing.assert_allclose(pf.channels["P"], mat["P_slow"], rtol=1e-10, atol=1e-10)

    def test_temperature_T1(self, file_pair):
        """Temperature T1 should exactly match MATLAB T1_slow."""
        pf, mat, _ = file_pair
        np.testing.assert_allclose(pf.channels["T1"], mat["T1_slow"], rtol=1e-10, atol=1e-10)

    def test_temperature_T2(self, file_pair):
        """Temperature T2 should exactly match MATLAB T2_slow."""
        pf, mat, _ = file_pair
        np.testing.assert_allclose(pf.channels["T2"], mat["T2_slow"], rtol=1e-10, atol=1e-10)


# ---------------------------------------------------------------------------
# Channel conversion: fast-rate
# ---------------------------------------------------------------------------


class TestFastChannels:
    """Compare fast-rate channels.

    With deconvolution, T1_dT1 and T2_dT2 are now high-resolution
    fast-rate signals that should exactly match MATLAB's T1_fast / T2_fast.
    P_dP is slow-rate (deconvolved at slow rate), so P_fast is obtained
    by interpolating the deconvolved P to fast rate.
    """

    def test_pressure_fast(self, file_pair):
        """P interpolated to fast rate should match MATLAB P_fast."""
        pf, mat, _ = file_pair
        py_P_fast = np.interp(pf.t_fast, pf.t_slow, pf.channels["P"])
        ml_P_fast = mat["P_fast"]
        np.testing.assert_allclose(py_P_fast, ml_P_fast, rtol=1e-5, atol=0.05)

    def test_temperature_T1_fast(self, file_pair):
        """T1_dT1 (deconvolved fast-rate) should exactly match MATLAB T1_fast."""
        pf, mat, _ = file_pair
        np.testing.assert_allclose(pf.channels["T1_dT1"], mat["T1_fast"], rtol=1e-10, atol=1e-10)

    def test_temperature_T2_fast(self, file_pair):
        """T2_dT2 (deconvolved fast-rate) should exactly match MATLAB T2_fast."""
        pf, mat, _ = file_pair
        np.testing.assert_allclose(pf.channels["T2_dT2"], mat["T2_fast"], rtol=1e-10, atol=1e-10)

    def test_accelerometer_Ax(self, file_pair):
        """Ax should exactly match MATLAB Ax."""
        pf, mat, _ = file_pair
        np.testing.assert_allclose(pf.channels["Ax"], mat["Ax"], rtol=1e-10, atol=1e-10)

    def test_accelerometer_Ay(self, file_pair):
        """Ay should exactly match MATLAB Ay."""
        pf, mat, _ = file_pair
        np.testing.assert_allclose(pf.channels["Ay"], mat["Ay"], rtol=1e-10, atol=1e-10)

    def test_shear_conversion_factor(self, file_pair):
        """Python shear = MATLAB shear * speed^2 (ODAS divides by speed^2)."""
        pf, mat, _ = file_pair
        py_sh1 = pf.channels["sh1"]
        ml_sh1 = mat["sh1"]
        ml_speed = mat["speed_fast"]
        reconstructed = ml_sh1 * ml_speed**2
        mask = ml_speed > 0.1
        if np.any(mask):
            np.testing.assert_allclose(py_sh1[mask], reconstructed[mask], rtol=1e-6, atol=1e-6)


# ---------------------------------------------------------------------------
# Fall rate and speed
# ---------------------------------------------------------------------------


class TestFallRate:
    def test_fall_rate_sign_and_magnitude(self, file_pair):
        """Python fall rate should match MATLAB W_slow in sign and magnitude."""
        pf, mat, _ = file_pair
        from rsi_python.profile import _smooth_fall_rate

        py_W = _smooth_fall_rate(pf.channels["P"], pf.fs_slow)
        ml_W = mat["W_slow"]
        rms_diff = np.sqrt(np.mean((py_W - ml_W) ** 2))
        rms_signal = np.sqrt(np.mean(ml_W**2))
        relative_error = rms_diff / rms_signal
        assert relative_error < 0.15, f"Fall rate relative RMS error {relative_error:.3f} > 0.15"

    def test_speed_positive(self, file_pair):
        """Speed should be non-negative and correlate well with MATLAB."""
        pf, mat, _ = file_pair
        from rsi_python.profile import _smooth_fall_rate

        py_W = _smooth_fall_rate(pf.channels["P"], pf.fs_slow)
        py_speed = np.abs(py_W)
        ml_speed = mat["speed_slow"]
        fast_mask = (ml_speed > 0.3) & (py_speed > 0.3)
        if np.any(fast_mask):
            corr = np.corrcoef(py_speed[fast_mask], ml_speed[fast_mask])[0, 1]
            assert corr > 0.99, f"Speed correlation {corr:.4f} < 0.99"
            rel_diff = np.abs(py_speed[fast_mask] - ml_speed[fast_mask]) / ml_speed[fast_mask]
            assert np.median(rel_diff) < 0.02, (
                f"Median speed relative diff {np.median(rel_diff):.4f} > 0.02"
            )


# ---------------------------------------------------------------------------
# Profile detection
# ---------------------------------------------------------------------------


class TestProfiles:
    def test_profiles_found(self, file_pair):
        """Should detect at least one profile (skip short/transit files)."""
        pf, _mat, _ = file_pair
        from rsi_python.profile import _smooth_fall_rate, get_profiles

        P = pf.channels["P"]
        if P.max() < 1.0:
            pytest.skip("File does not reach profiling depth")
        W = _smooth_fall_rate(P, pf.fs_slow)
        profiles = get_profiles(
            P, W, pf.fs_slow, P_min=0.5, W_min=0.3, direction="down", min_duration=7.0
        )
        assert len(profiles) >= 1, "No profiles detected"

    def test_most_profiles_reach_depth(self, file_pair):
        """Most profiles should reach at least 20 dbar."""
        pf, _mat, _ = file_pair
        from rsi_python.profile import _smooth_fall_rate, get_profiles

        P = pf.channels["P"]
        W = _smooth_fall_rate(P, pf.fs_slow)
        profiles = get_profiles(
            P, W, pf.fs_slow, P_min=0.5, W_min=0.3, direction="down", min_duration=7.0
        )
        # All profiles should at least exceed P_min
        for i, (s, e) in enumerate(profiles):
            assert P[s:e].max() > 0.5, f"Profile {i}: max P < P_min"

    def test_profiles_non_overlapping(self, file_pair):
        """Profiles should not overlap."""
        pf, _mat, _ = file_pair
        from rsi_python.profile import _smooth_fall_rate, get_profiles

        P = pf.channels["P"]
        W = _smooth_fall_rate(P, pf.fs_slow)
        profiles = get_profiles(
            P, W, pf.fs_slow, P_min=0.5, W_min=0.3, direction="down", min_duration=7.0
        )
        for i in range(len(profiles) - 1):
            assert profiles[i][1] < profiles[i + 1][0], (
                f"Profiles {i} and {i + 1} overlap: {profiles[i]} vs {profiles[i + 1]}"
            )


# ---------------------------------------------------------------------------
# Epsilon extraction
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def eps_results(file_pair, cached_get_diss):
    _, _, p_path = file_pair
    results = cached_get_diss(p_path, fft_length=256, goodman=True)
    if len(results) == 0:
        pytest.skip("No profiles detected in this file")
    return results


class TestEpsilon:
    def test_epsilon_all_profiles(self, eps_results):
        """Should produce epsilon for detected profiles."""
        assert len(eps_results) >= 1, f"Expected >=1 profiles, got {len(eps_results)}"

    def test_epsilon_physical_range(self, eps_results):
        """Epsilon should be in physically plausible range for ocean."""
        for i, ds in enumerate(eps_results):
            eps = ds["epsilon"].values
            valid = eps[np.isfinite(eps) & (eps > 0)]
            assert len(valid) > 0, f"Profile {i}: no valid epsilon values"
            assert np.min(valid) > 1e-14, f"Profile {i}: min epsilon {np.min(valid):.2e} too small"
            assert np.max(valid) < 10.0, f"Profile {i}: max epsilon {np.max(valid):.2e} too large"

    def test_epsilon_speed_reasonable(self, eps_results):
        """Profiling speed should be in [0.01, 3.0] m/s."""
        for i, ds in enumerate(eps_results):
            speed = ds["speed"].values
            valid = speed[np.isfinite(speed)]
            assert np.all(valid >= 0.01), f"Profile {i}: speed too low"
            assert np.all(valid < 3.0), f"Profile {i}: speed too high"

    def test_epsilon_viscosity(self, eps_results):
        """Kinematic viscosity should be ~1e-6 m^2/s for tropical ocean."""
        for i, ds in enumerate(eps_results):
            nu = ds["nu"].values
            valid = nu[np.isfinite(nu)]
            assert len(valid) > 0
            assert np.all(valid > 5e-7), f"Profile {i}: viscosity too low"
            assert np.all(valid < 2e-6), f"Profile {i}: viscosity too high"

    def test_qc_fom(self, eps_results):
        """Figure of merit should cluster near 1.0 for good data."""
        all_fom = []
        for ds in eps_results:
            fom = ds["fom"].values
            valid = fom[np.isfinite(fom)]
            all_fom.extend(valid.tolist())
        all_fom = np.array(all_fom)
        median_fom = np.median(all_fom)
        assert 0.3 < median_fom < 3.0, f"Median FOM {median_fom:.2f} outside [0.3, 3.0]"

    def test_qc_K_max_ratio(self, eps_results):
        """K_max_ratio > 0 indicates spectral resolution."""
        all_kmr = []
        for ds in eps_results:
            kmr = ds["K_max_ratio"].values
            valid = kmr[np.isfinite(kmr)]
            all_kmr.extend(valid.tolist())
        all_kmr = np.array(all_kmr)
        assert np.all(all_kmr > 0), "K_max_ratio should be positive"

    def test_epsilon_two_probes(self, eps_results):
        """Both shear probes should produce similar epsilon (within 1 decade)."""
        for i, ds in enumerate(eps_results):
            eps = ds["epsilon"].values
            if eps.shape[0] >= 2:
                e1 = eps[0]
                e2 = eps[1]
                valid = np.isfinite(e1) & np.isfinite(e2) & (e1 > 0) & (e2 > 0)
                if np.sum(valid) > 5:
                    ratio = np.abs(np.log10(e1[valid]) - np.log10(e2[valid]))
                    median_ratio = np.median(ratio)
                    assert median_ratio < 1.0, (
                        f"Profile {i}: sh1/sh2 median log10 diff {median_ratio:.2f} > 1 decade"
                    )

    def test_nasmyth_spectrum_shape(self, eps_results):
        """Nasmyth spectrum should have correct shape and be positive."""
        ds = eps_results[0]
        nas = ds["spec_nasmyth"].values
        assert nas.ndim == 3  # (probe, freq, time)
        valid = nas[np.isfinite(nas)]
        assert np.all(valid > 0), "Nasmyth spectrum should be positive"


# ---------------------------------------------------------------------------
# Consistency: Python pipeline vs MATLAB channels
# ---------------------------------------------------------------------------


class TestCrossConsistency:
    def test_epsilon_from_matlab_channels(self, eps_results):
        """Epsilon from Python pipeline should produce valid results."""
        ds = eps_results[0]
        eps_py = ds["epsilon"].values
        P_py = ds["P_mean"].values
        valid = np.isfinite(eps_py[0]) & (eps_py[0] > 0) & np.isfinite(P_py)
        assert np.sum(valid) > 5, "Not enough valid epsilon estimates"

    def test_matlab_python_temperature_consistency(self, file_pair):
        """Python T1 (slow, deconvolved) should match MATLAB T1_slow exactly."""
        pf, mat, _ = file_pair
        np.testing.assert_allclose(pf.channels["T1"], mat["T1_slow"], rtol=1e-10, atol=1e-10)
