# Integration tests for odas_tpw.scor160
"""End-to-end pipeline tests: L1→L2→L3→L4."""

import numpy as np
import pytest

from odas_tpw.scor160.io import L1Data, L2Params, L3Params
from odas_tpw.scor160.l2 import process_l2
from odas_tpw.scor160.l3 import process_l3
from odas_tpw.scor160.l4 import process_l4
from odas_tpw.scor160.nasmyth import nasmyth


def _synthetic_l1(
    n_time=50000,
    n_shear=2,
    n_vib=2,
    fs=512.0,
    epsilon=1e-8,
    nu=1.3e-6,
    speed=0.6,
):
    """Create a synthetic L1Data with Nasmyth-like shear signals.

    The shear signal is generated by filtering white noise through
    a spectral shape that approximates a Nasmyth spectrum, providing
    a more realistic test than pure white noise.
    """
    rng = np.random.default_rng(42)
    time = np.arange(n_time) / fs / 86400

    # Pressure ramp: 5 → 100 dbar
    pres = np.linspace(5, 100, n_time)

    # Generate shear with Nasmyth spectral shape
    # Create white noise, FFT, shape by sqrt(Nasmyth), inverse FFT
    shear = np.zeros((n_shear, n_time))
    freqs = np.fft.rfftfreq(n_time, 1 / fs)
    k = freqs / speed  # wavenumber
    nas_spec = nasmyth(epsilon, nu, k + 1e-30)
    nas_spec[0] = 0
    # Target PSD in frequency domain: Ψ(f) = Ψ(k) / W
    target_psd = nas_spec / speed
    # Amplitude filter: sqrt(PSD * df) where df = fs/n_time
    df = fs / n_time
    amplitude_filter = np.sqrt(np.maximum(target_psd * df, 0))

    for i in range(n_shear):
        noise = rng.standard_normal(n_time)
        noise_fft = np.fft.rfft(noise)
        shaped = noise_fft * amplitude_filter
        shear[i] = np.fft.irfft(shaped, n=n_time)

    # Vibration: small signal (sinusoidal + noise)
    vib = np.zeros((n_vib, n_time))
    t = np.arange(n_time) / fs
    for i in range(n_vib):
        vib[i] = 0.001 * np.sin(2 * np.pi * 20 * t) + 0.0005 * rng.standard_normal(n_time)

    return L1Data(
        time=time,
        pres=pres,
        shear=shear,
        vib=vib,
        vib_type="ACC",
        fs_fast=fs,
        f_AA=98.0,
        vehicle="vmp",
        profile_dir="down",
        time_reference_year=2024,
        temp=np.full(n_time, 10.0),
    )


@pytest.fixture
def l1_data():
    return _synthetic_l1()


@pytest.fixture
def l2_params():
    return L2Params(
        HP_cut=0.25,
        despike_sh=np.array([8.0, 0.5, 0.04]),
        despike_A=np.array([np.inf, 0.5, 0.04]),
        profile_min_W=0.05,
        profile_min_P=2.0,
        profile_min_duration=5.0,
        speed_tau=1.5,
    )


@pytest.fixture
def l3_params():
    return L3Params(
        fft_length=256,
        diss_length=2048,
        overlap=1024,
        HP_cut=0.25,
        fs_fast=512.0,
        goodman=True,
    )


class TestFullPipeline:
    """Test the complete L1→L2→L3→L4 pipeline."""

    def test_pipeline_runs(self, l1_data, l2_params, l3_params):
        """Pipeline should run without errors on synthetic data."""
        l2 = process_l2(l1_data, l2_params)
        l3 = process_l3(l2, l1_data, l3_params)
        l4 = process_l4(l3, f_AA=l1_data.f_AA)

        assert l2.shear.shape[1] == l1_data.n_time
        assert l3.n_spectra > 0
        assert l4.n_spectra == l3.n_spectra

    def test_epsilon_positive_and_finite(self, l1_data, l2_params, l3_params):
        """Recovered epsilon values should be positive and finite."""
        l2 = process_l2(l1_data, l2_params)
        l3 = process_l3(l2, l1_data, l3_params)
        l4 = process_l4(l3, f_AA=l1_data.f_AA)

        for i in range(l4.n_shear):
            valid = np.isfinite(l4.epsi[i]) & (l4.epsi[i] > 0)
            # Most spectra should produce finite positive epsilon
            assert valid.sum() > l4.n_spectra * 0.5, (
                f"probe {i}: only {valid.sum()}/{l4.n_spectra} "
                f"finite positive epsilon values"
            )

    def test_all_outputs_finite(self, l1_data, l2_params, l3_params):
        """Key outputs should be finite (not NaN/Inf) for valid data."""
        l2 = process_l2(l1_data, l2_params)
        l3 = process_l3(l2, l1_data, l3_params)
        l4 = process_l4(l3, f_AA=l1_data.f_AA)

        assert np.all(np.isfinite(l4.time))
        assert np.all(np.isfinite(l4.pres))
        # Epsilon may have NaN for edge cases, but most should be finite
        for i in range(l4.n_shear):
            frac_finite = np.mean(np.isfinite(l4.epsi[i]))
            assert frac_finite > 0.5

    def test_qc_flags_computed(self, l1_data, l2_params, l3_params):
        """QC flags should be computed for all spectra (not all NaN)."""
        l2 = process_l2(l1_data, l2_params)
        l3 = process_l3(l2, l1_data, l3_params)
        l4 = process_l4(l3, f_AA=l1_data.f_AA)

        # Flags should be valid (0, 1, 16, 17, or 255)
        valid_flags = {0, 1, 16, 17, 255}
        for i in range(l4.n_shear):
            for j in range(l4.n_spectra):
                assert l4.epsi_flags[i, j] in valid_flags

    def test_epsi_final_computed(self, l1_data, l2_params, l3_params):
        """EPSI_FINAL should be computed for most windows."""
        l2 = process_l2(l1_data, l2_params)
        l3 = process_l3(l2, l1_data, l3_params)
        l4 = process_l4(l3, f_AA=l1_data.f_AA)

        frac_finite = np.mean(np.isfinite(l4.epsi_final))
        assert frac_finite > 0.3


class TestPipelineVariations:
    """Test pipeline with different configurations."""

    def test_no_goodman(self, l1_data, l2_params, l3_params):
        """Pipeline should work without Goodman cleaning."""
        l3_params.goodman = False
        l2 = process_l2(l1_data, l2_params)
        l3 = process_l3(l2, l1_data, l3_params)
        l4 = process_l4(l3, f_AA=l1_data.f_AA)
        assert l4.n_spectra > 0

    def test_no_despike(self, l1_data, l2_params, l3_params):
        """Pipeline should work with despiking disabled."""
        l2_params.despike_sh = np.array([np.inf, 0.5, 0.04])
        l2 = process_l2(l1_data, l2_params)
        l3 = process_l3(l2, l1_data, l3_params)
        l4 = process_l4(l3, f_AA=l1_data.f_AA)
        assert l4.n_spectra > 0

    def test_single_probe(self, l2_params, l3_params):
        """Pipeline should work with a single shear probe."""
        l1 = _synthetic_l1(n_shear=1, n_vib=2)
        l2 = process_l2(l1, l2_params)
        l3 = process_l3(l2, l1, l3_params)
        l4 = process_l4(l3, f_AA=l1.f_AA)
        assert l4.n_shear == 1
        assert l4.n_spectra > 0

    def test_no_vibration(self, l2_params, l3_params):
        """Pipeline should work with no vibration sensors."""
        l1 = _synthetic_l1(n_vib=0)
        l1.vib = np.zeros((0, l1.n_time))
        l2 = process_l2(l1, l2_params)
        l3 = process_l3(l2, l1, l3_params)
        l4 = process_l4(l3, f_AA=l1.f_AA)
        assert l4.n_spectra > 0

    def test_different_fft_length(self, l1_data, l2_params, l3_params):
        """Pipeline should work with different FFT lengths."""
        l3_params.fft_length = 512
        l3_params.diss_length = 4096
        l3_params.overlap = 2048
        l2 = process_l2(l1_data, l2_params)
        l3 = process_l3(l2, l1_data, l3_params)
        l4 = process_l4(l3, f_AA=l1_data.f_AA)
        assert l4.n_spectra > 0
        assert l3.n_wavenumber == 257  # 512/2+1

    def test_high_epsilon_signal(self, l2_params, l3_params):
        """Pipeline should work with high-epsilon signals (ISR method)."""
        l1 = _synthetic_l1(epsilon=1e-4)
        l2 = process_l2(l1, l2_params)
        l3 = process_l3(l2, l1, l3_params)
        l4 = process_l4(l3, f_AA=l1.f_AA)
        # Should use ISR method for high epsilon
        assert l4.n_spectra > 0


class TestPipelineConsistency:
    """Test consistency properties of the pipeline."""

    def test_spectra_count_matches(self, l1_data, l2_params, l3_params):
        """L4 should have same number of spectra as L3."""
        l2 = process_l2(l1_data, l2_params)
        l3 = process_l3(l2, l1_data, l3_params)
        l4 = process_l4(l3, f_AA=l1_data.f_AA)
        assert l4.n_spectra == l3.n_spectra

    def test_time_monotonic(self, l1_data, l2_params, l3_params):
        """Output time arrays should be monotonically increasing."""
        l2 = process_l2(l1_data, l2_params)
        l3 = process_l3(l2, l1_data, l3_params)
        assert np.all(np.diff(l3.time) > 0)

    def test_pressure_monotonic_downcast(self, l1_data, l2_params, l3_params):
        """For a downcast, L3 pressure should be monotonically increasing."""
        l2 = process_l2(l1_data, l2_params)
        l3 = process_l3(l2, l1_data, l3_params)
        assert np.all(np.diff(l3.pres) > 0)
