# Mar-2026, Claude and Pat Welch, pat@mousebrains.com
"""Validate Python deconvolution against MATLAB for ALL .p file pairs.

Compares Python PFile channel conversion against *_p2mat.nc files
generated by matlab/generate_odas_p2mat_nc.m.

Runs exact-match comparisons on P, T1, T2 (slow-rate) and T1_dT1, T2_dT2
(fast-rate) for every file in VMP/.
"""

import os
from pathlib import Path

import numpy as np
import pytest

netCDF4 = pytest.importorskip("netCDF4")

pytestmark = pytest.mark.matlab

VMP_DIR = Path(__file__).parents[1] / "VMP"

# Discover all matched _p2mat.nc / .p pairs.
# MAX_MATLAB_FILES controls how many files to test (default 5, 0 = all).
_pairs = []
if VMP_DIR.exists():
    for nc_path in sorted(VMP_DIR.glob("*_p2mat.nc")):
        stem = nc_path.stem.replace("_p2mat", "")
        p_path = nc_path.with_name(stem + ".p")
        if p_path.exists():
            _pairs.append((p_path, nc_path))

_max = int(os.environ.get("MAX_MATLAB_FILES", "12"))
if _max and len(_pairs) > _max:
    _step = len(_pairs) / _max
    _pairs = [_pairs[int(i * _step)] for i in range(_max)]


def _file_id(pair):
    return pair[0].stem.split("_")[-1]


def _load_p2mat(nc_path: Path) -> dict:
    """Load a *_p2mat.nc file.

    Returns a dict mapping variable names to squeezed numpy arrays,
    plus global attributes (fs_fast, fs_slow).
    """
    out = {}
    with netCDF4.Dataset(str(nc_path), "r") as ds:
        for attr in ds.ncattrs():
            out[attr] = ds.getncattr(attr)
        for vname in ds.variables:
            out[vname] = np.squeeze(ds.variables[vname][:])
    return out


@pytest.fixture(scope="module", params=_pairs, ids=[_file_id(p) for p in _pairs])
def file_pair(request):
    """Yield (PFile, nc_dict) for each matched file pair."""
    p_path, nc_path = request.param
    from microstructure_tpw.rsi.p_file import PFile

    pf = PFile(p_path)
    ref = _load_p2mat(nc_path)
    return pf, ref


class TestAllFilesExactMatch:
    """Every .p/_p2mat.nc pair should produce exact channel matches."""

    def test_sampling_rates(self, file_pair):
        pf, ref = file_pair
        np.testing.assert_allclose(pf.fs_fast, float(ref["fs_fast"]), rtol=1e-10)
        np.testing.assert_allclose(pf.fs_slow, float(ref["fs_slow"]), rtol=1e-10)

    def test_array_lengths(self, file_pair):
        pf, ref = file_pair
        assert pf.t_fast.shape == ref["t_fast"].shape, (
            f"t_fast: Python {pf.t_fast.shape} vs MATLAB {ref['t_fast'].shape}"
        )
        assert pf.t_slow.shape == ref["t_slow"].shape, (
            f"t_slow: Python {pf.t_slow.shape} vs MATLAB {ref['t_slow'].shape}"
        )

    def test_pressure_slow(self, file_pair):
        pf, ref = file_pair
        np.testing.assert_allclose(pf.channels["P"], ref["P_slow"], rtol=1e-10, atol=1e-10)

    def test_temperature_T1_slow(self, file_pair):
        pf, ref = file_pair
        np.testing.assert_allclose(pf.channels["T1"], ref["T1_slow"], rtol=1e-10, atol=1e-10)

    def test_temperature_T2_slow(self, file_pair):
        pf, ref = file_pair
        np.testing.assert_allclose(pf.channels["T2"], ref["T2_slow"], rtol=1e-10, atol=1e-10)

    def test_temperature_T1_fast(self, file_pair):
        pf, ref = file_pair
        np.testing.assert_allclose(pf.channels["T1_dT1"], ref["T1_fast"], rtol=1e-10, atol=1e-10)

    def test_temperature_T2_fast(self, file_pair):
        pf, ref = file_pair
        np.testing.assert_allclose(pf.channels["T2_dT2"], ref["T2_fast"], rtol=1e-10, atol=1e-10)

    def test_shear_speed_consistency(self, file_pair):
        """Python shear * speed^-2 should equal MATLAB shear (du/dz)."""
        pf, ref = file_pair
        py_sh1 = pf.channels["sh1"]
        ml_sh1 = ref["sh1"]
        ml_speed = ref["speed_fast"]

        reconstructed = ml_sh1 * ml_speed**2
        mask = ml_speed > 0.1
        if np.any(mask):
            np.testing.assert_allclose(py_sh1[mask], reconstructed[mask], rtol=1e-6, atol=1e-6)
