# Mar-2026, Claude and Pat Welch, pat@mousebrains.com
"""Validate new pipeline (L1→L2→L3→L4) against MATLAB reference data.

Compares the scor160-based pipeline output against *_validation.nc and
*_scalar_spectra.nc files generated by MATLAB/ODAS.

Unlike test_matlab_epsilon.py (which uses the old get_diss path), this
exercises the full pipeline: pfile_to_l1data → process_l2 → process_l3
→ process_l4 for epsilon, and process_l2_chi → process_l3_chi for scalar
spectra.
"""

import os
from pathlib import Path

import numpy as np
import pytest

netCDF4 = pytest.importorskip("netCDF4")

pytestmark = pytest.mark.matlab

VMP_DIR = Path(__file__).parents[1] / "VMP"

# ---------------------------------------------------------------------------
# File discovery — same pattern as test_matlab_epsilon.py
# MAX_MATLAB_FILES controls how many files to test (default 12, 0 = all).
# ---------------------------------------------------------------------------

_val_files = sorted(VMP_DIR.glob("*_validation.nc")) if VMP_DIR.exists() else []
_scalar_files = sorted(VMP_DIR.glob("*_scalar_spectra.nc")) if VMP_DIR.exists() else []
_max = int(os.environ.get("MAX_MATLAB_FILES", "12"))
if _max and len(_val_files) > _max:
    _step = len(_val_files) / _max
    _val_files = [_val_files[int(i * _step)] for i in range(_max)]
if _max and len(_scalar_files) > _max:
    _step = len(_scalar_files) / _max
    _scalar_files = [_scalar_files[int(i * _step)] for i in range(_max)]


def _file_id(path):
    stem = path.stem.replace("_validation", "").replace("_scalar_spectra", "")
    return stem.split("_")[-1]


# ---------------------------------------------------------------------------
# Session-scoped caches for expensive pipeline runs
# ---------------------------------------------------------------------------

_eps_cache = {}
_chi_cache = {}


def _cached_pipeline_epsilon(p_path, val):
    key = Path(p_path).resolve()
    if key not in _eps_cache:
        _eps_cache[key] = _run_pipeline_epsilon(p_path, val)
    return _eps_cache[key]


def _cached_pipeline_chi(p_path, val):
    key = Path(p_path).resolve()
    if key not in _chi_cache:
        _chi_cache[key] = _run_pipeline_chi(p_path, val)
    return _chi_cache[key]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _load_validation(nc_path: Path) -> dict:
    """Load a *_validation.nc file into a dict."""
    out = {}
    with netCDF4.Dataset(str(nc_path), "r") as ds:
        for attr in ds.ncattrs():
            out[attr] = ds.getncattr(attr)
        for vname in ds.variables:
            out[vname] = np.squeeze(ds.variables[vname][:])

        n_profiles = int(out["n_profiles"])
        keys = [
            "eps_all",
            "K_max_all",
            "FM_all",
            "mad_all",
            "method_all",
            "nu_all",
            "speed_all",
            "P_mean_all",
            "T_mean_all",
            "t_mean_all",
            "K_all",
            "F_all",
            "spec_sh_all",
        ]
        for k in keys:
            out[k] = [None] * n_profiles
        for pi in range(n_profiles):
            grp = ds.groups.get(f"profile_{pi + 1:03d}")
            if grp is None:
                continue
            out["eps_all"][pi] = np.squeeze(grp.variables["epsilon"][:])
            out["K_max_all"][pi] = np.squeeze(grp.variables["K_max"][:])
            out["FM_all"][pi] = np.squeeze(grp.variables["FM"][:])
            out["mad_all"][pi] = np.squeeze(grp.variables["mad"][:])
            out["method_all"][pi] = np.squeeze(grp.variables["method"][:])
            out["nu_all"][pi] = np.squeeze(grp.variables["nu"][:])
            out["speed_all"][pi] = np.squeeze(grp.variables["speed"][:])
            out["P_mean_all"][pi] = np.squeeze(grp.variables["P_mean"][:])
            out["T_mean_all"][pi] = np.squeeze(grp.variables["T_mean"][:])
            out["t_mean_all"][pi] = np.squeeze(grp.variables["t_mean"][:])
            out["K_all"][pi] = np.squeeze(grp.variables["K"][:])
            out["F_all"][pi] = np.squeeze(grp.variables["F"][:])
            if "spec_shear_clean" in grp.variables:
                out["spec_sh_all"][pi] = np.squeeze(grp.variables["spec_shear_clean"][:])
    return out


def _load_scalar_validation(nc_path: Path) -> dict:
    """Load a *_scalar_spectra.nc file into a dict."""
    out = {}
    with netCDF4.Dataset(str(nc_path), "r") as ds:
        for attr in ds.ncattrs():
            out[attr] = ds.getncattr(attr)
        for vname in ds.variables:
            out[vname] = np.squeeze(ds.variables[vname][:])

        n_profiles = int(out["n_profiles"])
        keys = [
            "scalar_spec_all",
            "K_scalar_all",
            "F_scalar_all",
            "speed_scalar_all",
            "P_scalar_all",
            "t_scalar_all",
        ]
        for k in keys:
            out[k] = [None] * n_profiles
        for pi in range(n_profiles):
            grp = ds.groups.get(f"profile_{pi + 1:03d}")
            if grp is None:
                continue
            out["scalar_spec_all"][pi] = np.squeeze(grp.variables["scalar_spec"][:])
            out["K_scalar_all"][pi] = np.squeeze(grp.variables["K"][:])
            out["F_scalar_all"][pi] = np.squeeze(grp.variables["F"][:])
            out["speed_scalar_all"][pi] = np.squeeze(grp.variables["speed"][:])
            out["P_scalar_all"][pi] = np.squeeze(grp.variables["P_mean"][:])
            out["t_scalar_all"][pi] = np.squeeze(grp.variables["t_mean"][:])
    return out


def _run_pipeline_epsilon(p_path, val):
    """Run the new pipeline L1→L2→L3→L4 for epsilon on each profile."""
    from odas_tpw.rsi.adapter import pfile_to_l1data
    from odas_tpw.rsi.p_file import PFile
    from odas_tpw.rsi.profile import _smooth_fall_rate, get_profiles
    from odas_tpw.scor160.io import L2Params, L3Params
    from odas_tpw.scor160.l2 import process_l2
    from odas_tpw.scor160.l3 import process_l3
    from odas_tpw.scor160.l4 import process_l4

    fft_length = int(val["fft_length"])
    diss_length = int(val["diss_length"])
    overlap = int(val["overlap"])
    HP_cut = float(val.get("HP_cut", 0.25))
    f_AA = float(val["f_AA"])
    fit_order = int(val["fit_order"])
    P_min = float(val["P_min"])
    W_min = float(val["W_min"])
    min_duration = float(val["min_duration"])

    pf = PFile(p_path)
    P_slow = pf.channels.get("P_dP", pf.channels.get("P"))
    W_slow = _smooth_fall_rate(P_slow, pf.fs_slow)
    profiles = get_profiles(
        P_slow,
        W_slow,
        pf.fs_slow,
        P_min=P_min,
        W_min=W_min,
        min_duration=min_duration,
    )

    results = []
    for s_slow, e_slow in profiles:
        l1 = pfile_to_l1data(pf, profile_slice=(s_slow, e_slow))

        l2_params = L2Params(
            HP_cut=HP_cut,
            despike_sh=np.array([8.0, 0.5, 0.04]),
            despike_A=np.array([np.inf, 0.5, 0.04]),
            profile_min_W=W_min,
            profile_min_P=P_min,
            profile_min_duration=min_duration,
            speed_tau=1.5,
        )
        l2 = process_l2(l1, l2_params)

        l3_params = L3Params(
            fft_length=fft_length,
            diss_length=diss_length,
            overlap=overlap,
            HP_cut=HP_cut,
            fs_fast=l1.fs_fast,
            goodman=True,
        )
        l3 = process_l3(l2, l1, l3_params)
        if l3.n_spectra == 0:
            continue

        l4 = process_l4(l3, temp=l3.temp, f_AA=f_AA, fit_order=fit_order)
        results.append(l4)

    return results, profiles


def _run_pipeline_chi(p_path, val):
    """Run the new pipeline L1→L2→L2chi→L3chi for scalar spectra."""
    from odas_tpw.chi.l2_chi import L2ChiParams, process_l2_chi
    from odas_tpw.chi.l3_chi import process_l3_chi
    from odas_tpw.rsi.adapter import pfile_to_l1data
    from odas_tpw.rsi.p_file import PFile
    from odas_tpw.rsi.profile import _smooth_fall_rate, get_profiles
    from odas_tpw.scor160.io import L2Params, L3Params
    from odas_tpw.scor160.l2 import process_l2

    fft_length = int(val["fft_length"])
    spec_length = int(val["spec_length"])
    overlap = int(val["overlap"])
    HP_cut = float(val.get("HP_cut", 0.25))

    pf = PFile(p_path)
    P_slow = pf.channels.get("P_dP", pf.channels.get("P"))
    W_slow = _smooth_fall_rate(P_slow, pf.fs_slow)
    profiles = get_profiles(
        P_slow,
        W_slow,
        pf.fs_slow,
        P_min=0.5,
        W_min=0.3,
        min_duration=7.0,
    )

    results = []
    for s_slow, e_slow in profiles:
        l1 = pfile_to_l1data(pf, profile_slice=(s_slow, e_slow))

        l2_params = L2Params(
            HP_cut=HP_cut,
            despike_sh=np.array([8.0, 0.5, 0.04]),
            despike_A=np.array([np.inf, 0.5, 0.04]),
            profile_min_W=0.3,
            profile_min_P=0.5,
            profile_min_duration=7.0,
            speed_tau=1.5,
        )
        l2 = process_l2(l1, l2_params)

        l2_chi_params = L2ChiParams(HP_cut=HP_cut)
        l2_chi = process_l2_chi(l1, l2, l2_chi_params)

        l3_chi_params = L3Params(
            fft_length=fft_length,
            diss_length=spec_length,
            overlap=overlap,
            HP_cut=HP_cut,
            fs_fast=l1.fs_fast,
            goodman=True,
        )

        l3_chi = process_l3_chi(l2_chi, l3_chi_params)
        if l3_chi.n_spectra > 0:
            results.append(l3_chi)

    return results, profiles


def _match_profiles_by_time(py_times, ml_times, max_diff=60.0):
    """Match profiles by first-estimate time. Returns (py_idx, ml_idx) pairs."""
    matched = []
    used_ml = set()
    for pi, py_t in enumerate(py_times):
        if np.isnan(py_t):
            continue
        best_mi = None
        best_diff = np.inf
        for mi, ml_t in enumerate(ml_times):
            if mi in used_ml or np.isnan(ml_t):
                continue
            diff = abs(py_t - ml_t)
            if diff < best_diff:
                best_diff = diff
                best_mi = mi
        if best_mi is not None and best_diff < max_diff:
            matched.append((pi, best_mi))
            used_ml.add(best_mi)
    return matched


def _ml_first_times(val, time_key, n_key="n_profiles"):
    """Extract first-estimate time per MATLAB profile."""
    times = []
    for i in range(int(val[n_key])):
        t = np.atleast_1d(val[time_key][i])
        valid = t[np.isfinite(t)]
        times.append(valid[0] if len(valid) > 0 else np.nan)
    return times


# ---------------------------------------------------------------------------
# Epsilon fixtures — parametrized over all validation files
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module", params=_val_files, ids=[_file_id(p) for p in _val_files])
def eps_validation_pair(request):
    """Yield (p_path, validation_dict) for each file with validation data."""
    val_path = request.param
    stem = val_path.stem.replace("_validation", "")
    p_path = val_path.with_name(stem + ".p")
    if not p_path.exists():
        pytest.skip(f"No .p file for {val_path.name}")
    return p_path, _load_validation(val_path)


@pytest.fixture(scope="module")
def epsilon_results(eps_validation_pair):
    """Run pipeline for epsilon and match against MATLAB. Cached per file."""
    p_path, val = eps_validation_pair
    l4_list, _profiles = _cached_pipeline_epsilon(p_path, val)

    py_times = [l4.time[0] if l4.n_spectra > 0 else np.nan for l4 in l4_list]
    ml_times = _ml_first_times(val, "t_mean_all")
    matched = _match_profiles_by_time(py_times, ml_times)
    return l4_list, val, matched


# ---------------------------------------------------------------------------
# Scalar spectra fixtures — parametrized over all scalar files
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module", params=_scalar_files, ids=[_file_id(p) for p in _scalar_files])
def scalar_validation_pair(request):
    """Yield (p_path, scalar_validation_dict) for each file."""
    val_path = request.param
    stem = val_path.stem.replace("_scalar_spectra", "")
    p_path = val_path.with_name(stem + ".p")
    if not p_path.exists():
        pytest.skip(f"No .p file for {val_path.name}")
    return p_path, _load_scalar_validation(val_path)


@pytest.fixture(scope="module")
def chi_results(scalar_validation_pair):
    """Run pipeline for chi spectra and match against MATLAB. Cached per file."""
    p_path, val = scalar_validation_pair
    l3_chi_list, _profiles = _cached_pipeline_chi(p_path, val)

    py_times = [l3.time[0] if l3.n_spectra > 0 else np.nan for l3 in l3_chi_list]
    ml_times = _ml_first_times(val, "t_scalar_all")
    matched = _match_profiles_by_time(py_times, ml_times)
    return l3_chi_list, val, matched


# ---------------------------------------------------------------------------
# Epsilon tests
# ---------------------------------------------------------------------------


class TestPipelineEpsilonVsMatlab:
    """Compare new pipeline epsilon against MATLAB get_diss_odas."""

    def test_profile_count(self, epsilon_results):
        """Pipeline should detect similar number of profiles as MATLAB."""
        l4_list, val, _matched = epsilon_results
        ml_n = int(val["n_profiles"])
        py_n = len(l4_list)
        assert abs(py_n - ml_n) <= 3, f"Profile count: Python {py_n} vs MATLAB {ml_n}"

    def test_most_profiles_matched(self, epsilon_results):
        l4_list, val, matched = epsilon_results
        ml_n = int(val["n_profiles"])
        py_n = len(l4_list)
        min_total = min(ml_n, py_n)
        if min_total >= 3:
            assert len(matched) >= min_total * 0.7

    def test_estimate_count(self, epsilon_results):
        """Number of spectral estimates should be close."""
        l4_list, val, matched = epsilon_results
        for pi, mi in matched:
            py_n = l4_list[pi].n_spectra
            ml_eps = np.atleast_2d(val["eps_all"][mi])
            ml_n = ml_eps.shape[0]
            ratio = py_n / ml_n if ml_n > 0 else 0
            assert 0.8 < ratio < 1.2, f"Profile {mi}: estimate count Python {py_n} vs MATLAB {ml_n}"

    def test_epsilon_order_of_magnitude(self, epsilon_results):
        """Epsilon should agree within ~1 decade."""
        l4_list, val, matched = epsilon_results

        for pi, mi in matched:
            l4 = l4_list[pi]
            py_eps = l4.epsi
            ml_eps = np.atleast_2d(val["eps_all"][mi])
            if ml_eps.shape[0] != py_eps.shape[0] and ml_eps.ndim == 2:
                ml_eps = ml_eps.T

            n_est = min(py_eps.shape[1], ml_eps.shape[1])
            for ci in range(min(py_eps.shape[0], ml_eps.shape[0])):
                py_e = py_eps[ci, :n_est]
                ml_e = ml_eps[ci, :n_est]
                valid = np.isfinite(py_e) & np.isfinite(ml_e) & (py_e > 0) & (ml_e > 0)
                if np.sum(valid) < 3:
                    continue
                log_diff = np.abs(np.log10(py_e[valid]) - np.log10(ml_e[valid]))
                median_diff = np.median(log_diff)
                assert median_diff < 1.0, (
                    f"Profile {mi}, probe {ci}: median log10(eps) diff {median_diff:.2f}"
                )

    def test_epsilon_correlation(self, epsilon_results):
        """Epsilon should be positively correlated in log-space."""
        l4_list, val, matched = epsilon_results
        all_corrs = []

        for pi, mi in matched:
            l4 = l4_list[pi]
            py_eps = l4.epsi
            ml_eps = np.atleast_2d(val["eps_all"][mi])
            if ml_eps.shape[0] != py_eps.shape[0] and ml_eps.ndim == 2:
                ml_eps = ml_eps.T

            n_est = min(py_eps.shape[1], ml_eps.shape[1])
            if n_est < 20:
                continue

            for ci in range(min(py_eps.shape[0], ml_eps.shape[0])):
                py_e = py_eps[ci, :n_est]
                ml_e = ml_eps[ci, :n_est]
                valid = np.isfinite(py_e) & np.isfinite(ml_e) & (py_e > 0) & (ml_e > 0)
                if np.sum(valid) < 20:
                    continue
                corr = np.corrcoef(np.log10(py_e[valid]), np.log10(ml_e[valid]))[0, 1]
                all_corrs.append(corr)
                assert corr > 0.0, f"Profile {mi}, probe {ci}: corr {corr:.3f}"

        if len(all_corrs) >= 5:
            frac_good = np.mean([c > 0.5 for c in all_corrs])
            assert frac_good > 0.6, f"Only {frac_good:.0%} have r > 0.5"

    def test_speed_match(self, epsilon_results):
        """Profiling speed should match."""
        l4_list, val, matched = epsilon_results

        for pi, mi in matched:
            l4 = l4_list[pi]
            py_spd = l4.pspd_rel
            ml_spd = np.atleast_1d(val["speed_all"][mi])
            n = min(len(py_spd), len(ml_spd))
            if n < 5:
                continue
            valid = np.isfinite(py_spd[:n]) & np.isfinite(ml_spd[:n])
            py_med = np.median(py_spd[:n][valid])
            ml_med = np.median(ml_spd[:n][valid])
            rel_diff = abs(py_med - ml_med) / ml_med
            assert rel_diff < 0.1, f"Profile {mi}: median speed diff {rel_diff:.3f}"

    def test_pressure_range(self, epsilon_results):
        """Pressure ranges should be similar."""
        l4_list, val, matched = epsilon_results

        for pi, mi in matched:
            l4 = l4_list[pi]
            py_P = l4.pres
            ml_P = np.atleast_1d(val["P_mean_all"][mi])
            py_max = np.nanmax(py_P)
            ml_max = np.nanmax(ml_P)
            if ml_max > 10:
                ratio = py_max / ml_max
                assert 0.7 < ratio < 1.3, (
                    f"Profile {mi}: max P ratio {ratio:.2f} "
                    f"(Python {py_max:.1f} vs MATLAB {ml_max:.1f})"
                )

    def test_speed_correlation(self, epsilon_results):
        """Per-estimate speed should be correlated."""
        l4_list, val, matched = epsilon_results

        for pi, mi in matched:
            l4 = l4_list[pi]
            py_spd = l4.pspd_rel
            ml_spd = np.atleast_1d(val["speed_all"][mi])
            n = min(len(py_spd), len(ml_spd))
            if n < 5:
                continue
            valid = np.isfinite(py_spd[:n]) & np.isfinite(ml_spd[:n])
            if np.sum(valid) < 5:
                continue
            corr = np.corrcoef(py_spd[:n][valid], ml_spd[:n][valid])[0, 1]
            assert corr > 0.75, f"Profile {mi}: speed corr {corr:.3f}"


# ---------------------------------------------------------------------------
# Scalar spectra (chi) tests
# ---------------------------------------------------------------------------


class TestPipelineChiSpectraVsMatlab:
    """Compare new pipeline scalar spectra against MATLAB get_scalar_spectra_odas."""

    def test_profile_count(self, chi_results):
        l3_chi_list, val, _matched = chi_results
        ml_n = int(val["n_profiles"])
        py_n = len(l3_chi_list)
        assert abs(py_n - ml_n) <= 3, f"Profile count: Python {py_n} vs MATLAB {ml_n}"

    def test_most_profiles_matched(self, chi_results):
        l3_chi_list, val, matched = chi_results
        ml_n = int(val["n_profiles"])
        py_n = len(l3_chi_list)
        min_total = min(ml_n, py_n)
        if min_total >= 3:
            assert len(matched) >= min_total * 0.7

    def test_estimate_count(self, chi_results):
        """Number of spectral windows should be close."""
        l3_chi_list, val, matched = chi_results
        for pi, mi in matched:
            l3 = l3_chi_list[pi]
            py_n = l3.n_spectra
            ml_spec = np.atleast_3d(val["scalar_spec_all"][mi])
            ml_n = ml_spec.shape[0]
            ratio = py_n / ml_n if ml_n > 0 else 0
            assert 0.8 < ratio < 1.2, f"Profile {mi}: estimate count Python {py_n} vs MATLAB {ml_n}"

    def test_scalar_spectra_log_agreement(self, chi_results):
        """Temperature gradient spectra should agree in log-space."""
        l3_chi_list, val, matched = chi_results

        for pi, mi in matched:
            l3 = l3_chi_list[pi]
            py_spec = l3.gradt_spec
            ml_spec = val["scalar_spec_all"][mi]
            ml_spec = np.atleast_3d(ml_spec)
            ml_spec = np.transpose(ml_spec, (1, 2, 0))

            n_probe = min(py_spec.shape[0], ml_spec.shape[0])
            n_est = min(py_spec.shape[2], ml_spec.shape[2])
            n_freq = min(py_spec.shape[1], ml_spec.shape[1])

            if n_est < 3:
                continue

            for ci in range(n_probe):
                log_diffs = []
                for j in range(n_est):
                    py_s = py_spec[ci, 1:n_freq, j]
                    ml_s = ml_spec[ci, 1:n_freq, j]
                    valid = np.isfinite(py_s) & np.isfinite(ml_s) & (py_s > 0) & (ml_s > 0)
                    if np.sum(valid) < 5:
                        continue
                    log_diff = np.abs(np.log10(py_s[valid]) - np.log10(ml_s[valid]))
                    log_diffs.extend(log_diff.tolist())

                if len(log_diffs) > 10:
                    median_diff = np.median(log_diffs)
                    assert median_diff < 0.5, (
                        f"Profile {mi}, therm {ci}: median log10 spec diff {median_diff:.3f}"
                    )

    def test_speed_consistency(self, chi_results):
        """Per-window speed should match."""
        l3_chi_list, val, matched = chi_results

        for pi, mi in matched:
            l3 = l3_chi_list[pi]
            py_spd = l3.pspd_rel
            ml_spd = np.atleast_1d(val["speed_scalar_all"][mi])
            n = min(len(py_spd), len(ml_spd))
            if n < 5:
                continue
            valid = (
                np.isfinite(py_spd[:n])
                & np.isfinite(ml_spd[:n])
                & (py_spd[:n] > 0.1)
                & (ml_spd[:n] > 0.1)
            )
            if np.sum(valid) < 5:
                continue
            corr = np.corrcoef(py_spd[:n][valid], ml_spd[:n][valid])[0, 1]
            assert corr > 0.75, f"Profile {mi}: speed corr {corr:.3f}"

    def test_wavenumber_vectors(self, chi_results):
        """K vectors should match (K = F/W)."""
        l3_chi_list, val, matched = chi_results

        for pi, mi in matched:
            l3 = l3_chi_list[pi]
            py_K = l3.kcyc
            ml_K = np.atleast_2d(val["K_scalar_all"][mi])
            if ml_K.shape[0] != py_K.shape[0]:
                ml_K = ml_K.T

            n_est = min(py_K.shape[1], ml_K.shape[1])
            n_freq = min(py_K.shape[0], ml_K.shape[0])

            for j in range(min(n_est, 5)):
                py_k = py_K[:n_freq, j]
                ml_k = ml_K[:n_freq, j]
                valid = np.isfinite(py_k) & np.isfinite(ml_k) & (py_k > 0) & (ml_k > 0)
                if np.sum(valid) < 3:
                    continue
                # K = F/speed, so K tolerance must accommodate speed differences
                np.testing.assert_allclose(
                    py_k[valid],
                    ml_k[valid],
                    rtol=0.15,
                    err_msg=f"Profile {mi}, est {j}: K mismatch",
                )

    def test_pressure_range(self, chi_results):
        """Pressure ranges should match."""
        l3_chi_list, val, matched = chi_results

        for pi, mi in matched:
            l3 = l3_chi_list[pi]
            py_P = l3.pres
            ml_P = np.atleast_1d(val["P_scalar_all"][mi])
            py_max = np.nanmax(py_P)
            ml_max = np.nanmax(ml_P)
            if ml_max > 10:
                ratio = py_max / ml_max
                assert 0.7 < ratio < 1.3, f"Profile {mi}: max P ratio {ratio:.2f}"
