# Mar-2026, Claude and Pat Welch, pat@mousebrains.com
"""Validate Python scalar spectra against MATLAB get_scalar_spectra_odas output.

Compares Python temperature gradient spectra (from chi pipeline) against
*_scalar_spectra.nc files generated by matlab/generate_scalar_spectra_nc.m.

This validates the full scalar spectrum chain:
  - First-difference correction
  - Bilinear transform correction
  - Goodman scalar cleaning
  - Frequency-to-wavenumber conversion

without depending on chi estimation.
"""

import os
from pathlib import Path

import numpy as np
import pytest

netCDF4 = pytest.importorskip("netCDF4")

pytestmark = pytest.mark.matlab

VMP_DIR = Path(__file__).parents[1] / "VMP"

# Discover scalar spectra validation files.
# MAX_MATLAB_FILES controls how many files to test (default 5, 0 = all).
_scalar_files = sorted(VMP_DIR.glob("*_scalar_spectra.nc")) if VMP_DIR.exists() else []
_max = int(os.environ.get("MAX_MATLAB_FILES", "12"))
if _max and len(_scalar_files) > _max:
    _step = len(_scalar_files) / _max
    _scalar_files = [_scalar_files[int(i * _step)] for i in range(_max)]


def _file_id(path):
    stem = path.stem.replace("_scalar_spectra", "")
    return stem.split("_")[-1]


def _load_scalar_validation(nc_path: Path) -> dict:
    """Load a *_scalar_spectra.nc file."""
    out = {}
    with netCDF4.Dataset(str(nc_path), "r") as ds:
        # Global attributes
        for attr in ds.ncattrs():
            out[attr] = ds.getncattr(attr)

        # Root-level variables
        for vname in ds.variables:
            out[vname] = np.squeeze(ds.variables[vname][:])

        # Per-profile groups → lists
        n_profiles = int(out["n_profiles"])
        list_keys = [
            "scalar_spec_all",
            "K_scalar_all",
            "F_scalar_all",
            "speed_scalar_all",
            "P_scalar_all",
            "t_scalar_all",
        ]
        for k in list_keys:
            out[k] = [None] * n_profiles

        for pi in range(n_profiles):
            grp_name = f"profile_{pi + 1:03d}"
            if grp_name not in ds.groups:
                continue
            grp = ds.groups[grp_name]

            out["scalar_spec_all"][pi] = np.squeeze(grp.variables["scalar_spec"][:])
            out["K_scalar_all"][pi] = np.squeeze(grp.variables["K"][:])
            out["F_scalar_all"][pi] = np.squeeze(grp.variables["F"][:])
            out["speed_scalar_all"][pi] = np.squeeze(grp.variables["speed"][:])
            out["P_scalar_all"][pi] = np.squeeze(grp.variables["P_mean"][:])
            out["t_scalar_all"][pi] = np.squeeze(grp.variables["t_mean"][:])

    return out


def _match_scalar_profiles(py_results, val):
    """Match Python and MATLAB profiles by mean time of first estimate."""
    n_ml = int(val["n_profiles"])

    ml_times = []
    for i in range(n_ml):
        t = val["t_scalar_all"][i]
        t = np.atleast_1d(t)
        valid = t[np.isfinite(t)]
        ml_times.append(valid[0] if len(valid) > 0 else np.nan)

    py_times = []
    for ds in py_results:
        t = ds.coords["t"].values
        valid = t[np.isfinite(t)]
        py_times.append(valid[0] if len(valid) > 0 else np.nan)

    matched = []
    used_ml = set()
    for pi, py_t in enumerate(py_times):
        if np.isnan(py_t):
            continue
        best_mi = None
        best_diff = np.inf
        for mi, ml_t in enumerate(ml_times):
            if mi in used_ml or np.isnan(ml_t):
                continue
            diff = abs(py_t - ml_t)
            if diff < best_diff:
                best_diff = diff
                best_mi = mi
        if best_mi is not None and best_diff < 60.0:
            matched.append((pi, best_mi))
            used_ml.add(best_mi)

    return matched


@pytest.fixture(scope="module", params=_scalar_files, ids=[_file_id(p) for p in _scalar_files])
def scalar_pair(request):
    """Yield (p_path, scalar_validation_dict) for each file."""
    val_path = request.param
    stem = val_path.stem.replace("_scalar_spectra", "")
    p_path = val_path.with_name(stem + ".p")
    if not p_path.exists():
        pytest.skip(f"No .p file for {val_path.name}")
    val = _load_scalar_validation(val_path)
    return p_path, val


@pytest.fixture(scope="module")
def matched_scalar(scalar_pair, cached_get_chi):
    """Run get_chi (Method 2) and match profiles against MATLAB."""
    p_path, val = scalar_pair
    results = cached_get_chi(p_path, fft_length=256, diss_length=512, overlap=256, goodman=True)
    matched = _match_scalar_profiles(results, val)
    return results, val, matched


class TestScalarSpectraVsMatlab:
    """Compare Python scalar spectra against MATLAB get_scalar_spectra_odas."""

    def test_profile_count(self, matched_scalar):
        """Should detect similar number of profiles."""
        results, val, _matched = matched_scalar
        ml_n = int(val["n_profiles"])
        py_n = len(results)
        assert abs(py_n - ml_n) <= 3, f"Profile count: Python {py_n} vs MATLAB {ml_n}"

    def test_most_profiles_matched(self, matched_scalar):
        """Most profiles should match."""
        results, val, matched = matched_scalar
        ml_n = int(val["n_profiles"])
        py_n = len(results)
        min_total = min(ml_n, py_n)
        if min_total >= 3:
            assert len(matched) >= min_total * 0.7, (
                f"Only {len(matched)}/{min_total} profiles matched"
            )

    def test_wavenumber_vectors(self, matched_scalar):
        """K vectors from Python and MATLAB should match (K = F/W)."""
        results, val, matched = matched_scalar

        for pi, mi in matched:
            py_K = results[pi]["K"].values  # (n_freq, n_est)
            ml_K = val["K_scalar_all"][mi]  # (n_est, n_freq) from NetCDF

            ml_K = np.atleast_2d(ml_K)
            if ml_K.shape[0] != py_K.shape[0]:
                ml_K = ml_K.T  # -> (n_freq, n_est)

            n_est = min(py_K.shape[1], ml_K.shape[1])
            n_freq = min(py_K.shape[0], ml_K.shape[0])

            for j in range(min(n_est, 5)):
                py_k = py_K[:n_freq, j]
                ml_k = ml_K[:n_freq, j]
                valid = np.isfinite(py_k) & np.isfinite(ml_k) & (py_k > 0) & (ml_k > 0)
                if np.sum(valid) < 3:
                    continue
                np.testing.assert_allclose(
                    py_k[valid],
                    ml_k[valid],
                    rtol=0.05,
                    err_msg=f"py_prof {pi} / ml_prof {mi}, est {j}: K mismatch",
                )

    def test_scalar_spectra_log_agreement(self, matched_scalar):
        """Temperature gradient spectra should agree in log-space.

        Compares Python spec_gradT against MATLAB scalar_spec.
        Both should be in wavenumber units (K^2 m^-1) with first-difference
        and bilinear corrections applied.
        """
        results, val, matched = matched_scalar

        for pi, mi in matched:
            py_spec = results[pi]["spec_gradT"].values  # (n_probe, n_freq, n_est)
            ml_spec = val["scalar_spec_all"][mi]
            # NetCDF shape: (n_est, n_therm, n_freq) — transpose to (n_therm, n_freq, n_est)

            ml_spec = np.atleast_3d(ml_spec)
            ml_spec = np.transpose(ml_spec, (1, 2, 0))

            n_probe = min(py_spec.shape[0], ml_spec.shape[0])
            n_est = min(py_spec.shape[2], ml_spec.shape[2])
            n_freq = min(py_spec.shape[1], ml_spec.shape[1])

            if n_est < 3:
                continue

            for ci in range(n_probe):
                log_diffs = []
                for j in range(n_est):
                    py_s = py_spec[ci, 1:n_freq, j]  # skip DC
                    ml_s = ml_spec[ci, 1:n_freq, j]
                    valid = np.isfinite(py_s) & np.isfinite(ml_s) & (py_s > 0) & (ml_s > 0)
                    if np.sum(valid) < 5:
                        continue
                    log_diff = np.abs(np.log10(py_s[valid]) - np.log10(ml_s[valid]))
                    log_diffs.extend(log_diff.tolist())

                if len(log_diffs) > 10:
                    median_diff = np.median(log_diffs)
                    assert median_diff < 0.5, (
                        f"py_prof {pi} / ml_prof {mi}, therm {ci}: "
                        f"median log10 scalar spec diff {median_diff:.3f} > 0.5"
                    )

    def test_speed_consistency(self, matched_scalar):
        """Mean speed per estimate should be similar."""
        results, val, matched = matched_scalar

        for pi, mi in matched:
            py_speed = results[pi]["speed"].values
            ml_speed = val["speed_scalar_all"][mi]
            ml_speed = np.atleast_1d(ml_speed)

            n_est = min(len(py_speed), len(ml_speed))
            if n_est < 5:
                continue
            valid = (
                np.isfinite(py_speed[:n_est])
                & np.isfinite(ml_speed[:n_est])
                & (py_speed[:n_est] > 0.1)
                & (ml_speed[:n_est] > 0.1)
            )
            if np.sum(valid) < 5:
                continue
            corr = np.corrcoef(py_speed[:n_est][valid], ml_speed[:n_est][valid])[0, 1]
            assert corr > 0.75, f"py_prof {pi} / ml_prof {mi}: speed corr {corr:.3f} < 0.75"
