#!/usr/bin/env python3
"""Compare PFile channel conversion against ODAS Matlab odas_p2mat output.

Loads a .p file with PFile and the matching *_allch.nc generated by
matlab/generate_all_channels_nc.m, then compares every channel that
exists in both.

Usage:
    python scripts/compare_allch.py VMP/ARCTERX_Thompson_2025_SN479_0002.p
    python scripts/compare_allch.py MR/AIOP2_SL685_0450.p
    python scripts/compare_allch.py VMP/*.p MR/*.p      # all files

If no arguments are given, processes the first VMP and first MR file.
"""

import sys
from pathlib import Path

import netCDF4 as nc
import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from odas_tpw.rsi.p_file import PFile

# ODAS's odas_p2mat stores two versions of deconvolved channels:
#   - Raw (pre-deconvolution): P, T1, T2, T1_dT1, T2_dT2, P_dP
#   - Deconvolved (post-deconvolution): P_slow, T1_slow, T1_fast, etc.
# PFile returns the deconvolved versions under the original names.
# We compare PFile channels against the ODAS *deconvolved* variables.

# NC variable → PFile channel name (deconvolved channels)
_DECONV_CHANNELS = {
    "P_slow": "P",
    "T1_slow": "T1",
    "T2_slow": "T2",
    "T1_fast": "T1_dT1",
    "T2_fast": "T2_dT2",
}

# Channels that match directly (same name, no deconvolution involved)
_DIRECT_CHANNELS = [
    "Ax", "Ay",
    "PV", "V_Bat",
    "Incl_X", "Incl_Y", "Incl_T",
    "JAC_C", "JAC_T",
    "Chlorophyll", "Turbidity",
    "DO", "DO_T",
    "U_EM", "EMC_Cur",
    "Gnd",
]

# Shear channels need special treatment (ODAS divides by speed^2)
_SHEAR_CHANNELS = ["sh1", "sh2"]


def load_allch(nc_path: Path) -> dict[str, np.ndarray]:
    """Load all variables from an _allch.nc file."""
    out = {}
    with nc.Dataset(str(nc_path), "r") as ds:
        for vname in ds.variables:
            out[vname] = np.squeeze(ds.variables[vname][:])
        for attr in ds.ncattrs():
            out[f"__attr__{attr}"] = ds.getncattr(attr)
    return out


def compare_channel(
    py: np.ndarray,
    ml: np.ndarray,
    name: str,
    *,
    rtol: float = 1e-10,
    atol: float = 1e-10,
) -> tuple[bool, str]:
    """Compare two arrays, return (passed, message)."""
    if py.shape != ml.shape:
        return False, f"shape mismatch: py={py.shape} ml={ml.shape}"

    if np.all(py == 0) and np.all(ml == 0):
        return True, "both all-zero"

    finite = np.isfinite(py) & np.isfinite(ml)
    if not np.any(finite):
        return True, "no finite values to compare"

    py_f = py[finite]
    ml_f = ml[finite]

    max_abs_diff = np.max(np.abs(py_f - ml_f))
    scale = np.max(np.abs(ml_f))
    max_rel_diff = max_abs_diff / scale if scale > 0 else max_abs_diff

    n_mismatch = np.sum(np.abs(py_f - ml_f) > atol + rtol * np.abs(ml_f))
    n_total = len(py_f)

    try:
        np.testing.assert_allclose(py_f, ml_f, rtol=rtol, atol=atol)
        return True, f"max_rel={max_rel_diff:.2e}, max_abs={max_abs_diff:.2e}"
    except AssertionError:
        return (
            False,
            f"max_rel={max_rel_diff:.2e}, max_abs={max_abs_diff:.2e}"
            f", mismatch={n_mismatch}/{n_total}",
        )


def compare_file(p_path: Path) -> list[dict]:
    """Compare one .p file against its _allch.nc reference."""
    nc_path = p_path.with_name(p_path.stem + "_allch.nc")
    if not nc_path.exists():
        print(f"  SKIP: {nc_path.name} not found")
        return []

    pf = PFile(p_path)
    ml = load_allch(nc_path)

    results = []

    # 1. Deconvolved channels (exact match expected)
    for nc_name, pf_name in _DECONV_CHANNELS.items():
        if pf_name not in pf.channels or nc_name not in ml:
            continue
        passed, msg = compare_channel(pf.channels[pf_name], ml[nc_name], nc_name)
        results.append({
            "channel": f"{pf_name} (vs {nc_name})",
            "passed": passed,
            "detail": msg,
        })

    # 2. Direct channels (no deconvolution, exact match expected)
    #    For DO/DO_T, ODAS applies a glitch filter (replaces raw=0 with
    #    the previous good value) that we don't replicate.  Exclude those
    #    samples from the comparison.
    for ch_name in _DIRECT_CHANNELS:
        if ch_name not in pf.channels or ch_name not in ml:
            continue
        py_data = pf.channels[ch_name]
        ml_data = ml[ch_name]
        if ch_name in ("DO", "DO_T") and ch_name in pf.channels_raw:
            raw = pf.channels_raw[ch_name]
            keep = raw != 0
            py_data = py_data[keep]
            ml_data = ml_data[keep]
            n_glitch = int(np.sum(~keep))
            glitch_note = f" (excluded {n_glitch} raw=0 glitch samples)"
        else:
            glitch_note = ""
        passed, msg = compare_channel(py_data, ml_data, ch_name)
        results.append({
            "channel": ch_name,
            "passed": passed,
            "detail": msg + glitch_note,
        })

    # 3. Shear channels: PFile stores raw shear (s⁻¹); ODAS divides by speed²
    for ch_name in _SHEAR_CHANNELS:
        if ch_name not in pf.channels or ch_name not in ml:
            continue
        speed_key = "speed_fast"
        if speed_key not in ml:
            continue
        speed = ml[speed_key]
        mask = speed > 0.05
        if not np.any(mask):
            continue
        reconstructed = ml[ch_name] * speed**2
        passed, msg = compare_channel(
            pf.channels[ch_name][mask], reconstructed[mask], ch_name,
            rtol=1e-6, atol=1e-6,
        )
        results.append({
            "channel": f"{ch_name} (py vs ml*speed²)",
            "passed": passed,
            "detail": msg,
        })

    # 4. Sampling rates
    fs_fast_match = np.isclose(pf.fs_fast, ml["__attr__fs_fast"], rtol=1e-10)
    results.append({
        "channel": "fs_fast",
        "passed": fs_fast_match,
        "detail": f"py={pf.fs_fast:.6f} ml={ml['__attr__fs_fast']:.6f}",
    })
    fs_slow_match = np.isclose(pf.fs_slow, ml["__attr__fs_slow"], rtol=1e-10)
    results.append({
        "channel": "fs_slow",
        "passed": fs_slow_match,
        "detail": f"py={pf.fs_slow:.6f} ml={ml['__attr__fs_slow']:.6f}",
    })

    return results


def print_results(p_path: Path, results: list[dict]) -> int:
    """Print comparison results, return number of failures."""
    print(f"\n{'=' * 78}")
    print(f"  {p_path}")
    print(f"{'=' * 78}")

    n_pass = sum(1 for r in results if r["passed"])
    n_fail = sum(1 for r in results if not r["passed"])

    for r in results:
        status = "PASS" if r["passed"] else "FAIL"
        print(f"  [{status}] {r['channel']:30s}  {r['detail']}")

    print(f"\n  {n_pass} passed, {n_fail} failed out of {len(results)} comparisons")
    return n_fail


def main():
    if len(sys.argv) > 1:
        p_files = []
        for arg in sys.argv[1:]:
            p = Path(arg)
            if p.is_file() and p.suffix.lower() == ".p":
                p_files.append(p)
    else:
        p_files = []
        for d in ["VMP", "MR"]:
            dp = Path(d)
            if dp.exists():
                first = sorted(dp.glob("*.p"))
                if first:
                    p_files.append(first[0])

    if not p_files:
        print("No .p files found. Usage: python scripts/compare_allch.py FILE.p ...")
        sys.exit(1)

    total_failures = 0
    for p_path in p_files:
        results = compare_file(p_path)
        if results:
            total_failures += print_results(p_path, results)

    print(f"\n{'=' * 78}")
    if total_failures == 0:
        print("  ALL COMPARISONS PASSED")
    else:
        print(f"  {total_failures} TOTAL FAILURES")
    print(f"{'=' * 78}")
    sys.exit(1 if total_failures else 0)


if __name__ == "__main__":
    main()
