#!/usr/bin/env python3
"""Generate sections.yaml for a SUNRISE VMP deployment.

ONE SECTION = ONE SURVEY LINE.

The ships ran parallel lines, turning at the end and running back the other
way (Pat: 2021 and 2022 for certain, 2019 probably). So a section must be cut
on the TURN, not only on a time gap -- the tow-yo often continues straight
through a turnaround, and a gap-only cut then lumps an out-and-back pair, or
four legs, into one "section" whose distance axis folds back on itself.

The track geometry confirms the pattern. Aspect ratio of the cast positions
and the concentration of inter-cast headings into the top 2 of 18 bins:

    2021   aspect  13-114   headings 93-99%   repeated lines on ONE axis
    2022   aspect 1.7-2.1   headings 73-77%   lines, groups spread over 180+ km
    2019   aspect 1.5/3.2   headings 41/72%   weaker; SN194 line-like, SN142 not

TWO-STAGE CUT.
  1. A 30 min gap between casts ends a RUN (transit, station change,
     overnight). Campaign-wide 99.0% of cast-to-cast gaps are under 5 min and
     only 0.39% fall between 5 and 45, so this threshold is not critical.
  2. Within a run, positions are projected onto that RUN's own principal axis
     (per-run, not survey-wide: in 2022 the line groups sit in different places
     and orientations) and split into MONOTONIC LEGS. A leg shorter than
     ``MIN_LEG_KM`` along-axis is merged into its neighbour, which is what
     keeps GPS jitter and the slow wander of a tow-yo from manufacturing turns.

Why not ``perturb mk-sections``: the built-in cuts on a gap only, so on this
survey pattern it produces the folded sections described above. Its output
schema is what is emitted here.

THE SECTIONS FILE CARRIES NO PATHS -- only names, time ranges and axis
choices. That is what lets ONE file serve both product trees:

    perturb-plot scalar --root VMP_results     --sections sections.yaml ...
    perturb-plot scalar --root VMP_results_bbl --sections sections.yaml ...
"""
from __future__ import annotations

import argparse
import glob
import os
import re
import sys
import warnings

import numpy as np
import xarray as xr

warnings.filterwarnings("ignore")

GAP_SECONDS = 1800.0
MIN_LEG_KM = 2.0
SMOOTH_CASTS = 5
MIN_CASTS = 5
STRAIGHT_MIN = 0.80  # below this a leg gets a time axis, not a distance axis


def newest_combo(analysis_dir: str) -> str | None:
    gens = sorted(
        g
        for g in glob.glob(os.path.join(analysis_dir, "VMP_results", "diss_combo_*"))
        if re.fullmatch(r"diss_combo_\d+", os.path.basename(g))
    )
    for g in reversed(gens):
        f = os.path.join(g, "combo.nc")
        if os.path.exists(f):
            return f
    return None


def leg_bounds(s: np.ndarray) -> list[int]:
    """Boundaries of the monotonic legs of ``s``."""
    n = len(s)
    if n < 2 * SMOOTH_CASTS:
        return [0, n]
    k = np.ones(SMOOTH_CASTS) / SMOOTH_CASTS
    ss = np.convolve(s, k, mode="same")
    ss[:SMOOTH_CASTS] = s[:SMOOTH_CASTS]
    ss[-SMOOTH_CASTS:] = s[-SMOOTH_CASTS:]
    sgn = np.sign(np.diff(ss))
    for i in range(1, len(sgn)):
        if sgn[i] == 0:
            sgn[i] = sgn[i - 1]
    b = [0] + [i + 1 for i in np.flatnonzero(np.diff(sgn) != 0)] + [n]
    out = [b[0]]
    for i in range(1, len(b)):
        if abs(s[min(b[i], n - 1)] - s[out[-1]]) >= MIN_LEG_KM or i == len(b) - 1:
            out.append(b[i])
    if out[-1] != n:
        out.append(n)
    return out


def build(analysis_dir: str, out_path: str) -> tuple[int, int]:
    combo = newest_combo(analysis_dir)
    if combo is None:
        print("  no combo product; skipped", file=sys.stderr)
        return (0, 0)
    ds = xr.open_dataset(combo)
    la = np.asarray(ds["lat"].values, float)
    lo = np.asarray(ds["lon"].values, float)
    st = np.asarray(ds["stime"].values).astype("datetime64[ns]")
    ds.close()

    m = np.isfinite(la) & np.isfinite(lo) & ~np.isnat(st)
    la, lo, st = la[m], lo[m], st[m]
    o = np.argsort(st)
    la, lo, st = la[o], lo[o], st[o]
    if st.size == 0:
        return (0, 0)

    t = st.astype("int64") / 1e9
    grp = np.concatenate(([0], np.cumsum(np.diff(t) > GAP_SECONDS)))

    def iso(x):
        return str(np.datetime64(x, "s")) + "Z"

    lines = [
        "# Plotting sections -- SUNRISE VMP.  GENERATED by make_sections.py;",
        "# regenerate rather than hand-editing.",
        "#",
        "# ONE SECTION = ONE SURVEY LINE. The ships ran parallel lines and turned",
        "# at the end, and the tow-yo often runs straight through the turn, so the",
        "# cut is a %g min gap (ends a run) PLUS a reversal along that run's own" % (GAP_SECONDS / 60),
        "# principal axis (ends a leg). A leg under %g km along-axis is merged," % MIN_LEG_KM,
        "# which keeps GPS jitter from manufacturing turns.",
        "#",
        "# NO PATHS HERE ON PURPOSE: the same file serves both product trees,",
        "#   perturb-plot scalar --root VMP_results     --sections sections.yaml",
        "#   perturb-plot scalar --root VMP_results_bbl --sections sections.yaml",
        "",
        "sections:",
        "",
        "  - name: full_timeseries",
        "    xaxis: {method: time}",
        "",
    ]

    n_line = 0
    n_run = int(grp.max()) + 1
    for g in np.unique(grp):
        k = np.flatnonzero(grp == g)
        if k.size < MIN_CASTS:
            continue
        lat0 = float(np.median(la[k]))
        x = (lo[k] - np.median(lo[k])) * 111320.0 * np.cos(np.radians(lat0)) / 1000.0
        y = (la[k] - lat0) * 111320.0 / 1000.0
        if k.size >= 2 * SMOOTH_CASTS:
            P = np.vstack([x - x.mean(), y - y.mean()])
            _, V = np.linalg.eigh(np.cov(P))
            ax = V[:, -1]
        else:
            ax = np.array([1.0, 0.0])
        s = x * ax[0] + y * ax[1]
        for a, b in zip(bd := leg_bounds(s), bd[1:]):
            if b - a < MIN_CASTS:
                continue
            seg = s[a:b]
            net = abs(seg[-1] - seg[0])
            path = float(np.abs(np.diff(seg)).sum())
            straight = net / path if path > 0 else 0.0
            n_line += 1
            span_h = (st[k][b - 1] - st[k][a]).astype("timedelta64[s]").astype(float) / 3600.0
            axis = (
                "{method: signed_distance, units: km}"
                if straight >= STRAIGHT_MIN and net >= MIN_LEG_KM
                else "{method: time}"
            )
            why = "" if straight >= STRAIGHT_MIN else "   # too curved for a distance axis"
            lines += [
                "  # %d casts, %.1f km net, %.2f h, straightness %.2f"
                % (b - a, net, span_h, straight),
                "  - name: line_%03d" % n_line,
                '    start: "%s"' % iso(st[k][a]),
                '    stop:  "%s"' % iso(st[k][b - 1]),
                "    xaxis: %s%s" % (axis, why),
                "",
            ]
    with open(out_path, "w") as fh:
        fh.write("\n".join(lines))
    return (n_run, n_line)


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("analysis_dirs", nargs="+")
    a = ap.parse_args()
    print("%-40s %6s %6s" % ("deployment", "runs", "lines"))
    for d in a.analysis_dirs:
        nr, nl = build(d, os.path.join(d, "sections.yaml"))
        print("%-40s %6d %6d" % (os.path.relpath(d), nr, nl))
